version: '3.4'

services:
  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tmp/tempo:/tmp/tempo
    networks:
      - mynetwork
  
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./tmp/prometheus:/prometheus
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./tmp/grafana/:/var/lib/grafana/
      - ./ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    ports:
      - "3000:3000"
    networks:
      - mynetwork
  
  otel-collector:
    container_name: otelcollector
    image: otel/opentelemetry-collector-contrib:latest
    command: [ --config=/etc/otel-collector-config.yml ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - prometheus
      - loki
      - tempo
    ports:
      - "4317:4317"  
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
